curiosidadesrussas/urls.py
from django.contrib import admin
from django.urls import include, path # modificar esta linha

urlpatterns = [
    path('', include('staticpages.urls')), # adicionar esta linha
    path('songs/', include('songs.urls')),
    path('admin/', admin.site.urls),
]

songs/urls.py
from django.urls import path

from . import views

app_name = 'songs'
urlpatterns = [
    path('', views.SongListView.as_view(), name='index'),
    path('create/', views.SongCreateView.as_view(), name='create'),
    path('<int:pk>/', views.SongDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', views.SongUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.SongDeleteView.as_view(), name='delete'),
    path('<int:post_id>/comment/', views.create_comment, name='comment'),
    path('category/<int:pk>', views.CategoryDetailView.as_view(), name='category'),
    path('categories/', views.CategoryListView.as_view(), name='categories'),
]

staticpages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('about/', views.about, name='about'),
    path('', views.index, name='index'),
    path('musicas/', views.musicas, name='musicas'),
]

songs/models.py
from django.db import models
from django.conf import settings
from datetime import datetime
from django.urls import reverse

class Song(models.Model):
    name = models.CharField(max_length=255)
    release_year = models.IntegerField()
    poster_url = models.URLField(max_length=200, null=True)

    def __str__(self):
        return f'{self.name} ({self.release_year})'




class Post(models.Model):
    name = models.CharField(max_length=255)
    lyrics = models.CharField(max_length=255)
    band = models.CharField(max_length=255)
    date = models.DateTimeField(default=datetime.now, blank=True)

    def __str__(self):
        return f'{self.name} ({self.band})'

class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    text = models.CharField(max_length=255)
    date = models.DateTimeField(default=datetime.now, blank=True)
    posts = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return f'"{self.text}" - {self.author.username}'

class Category(models.Model):
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    posts = models.ManyToManyField(Post, blank = True)

    def __str__(self):
        return f'{self.name}'

staticpages/models.py
from django.db import models

# Create your models here.

songs/forms.py
from django.forms import ModelForm
from .models import Post, Comment

class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = [
            'name',
            'band',
            'lyrics',
        ]
        labels = {
            'name': 'Título',
            'band': 'Banda',
            'lyrics': 'Letra',
        }

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = [
            'author',
            'text',
        ]
        labels = {
            'author': 'Usuário',
            'text': 'Comentário',
        }

songs/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .temp_data import movie_data
from django.http import HttpResponseRedirect
from .models import Song
from .models import Post, Comment, Category

from django.urls import reverse, reverse_lazy
from django.shortcuts import render, get_object_or_404


from .forms import PostForm, CommentForm

from django.views import generic







class SongListView(generic.ListView):
    model = Post
    template_name = 'songs/index.html' 

class SongDetailView(generic.DetailView):
    model = Post
    template_name = 'songs/detail.html'

class SongCreateView(generic.CreateView):
    model = Post
    fields = ['name', 'lyrics', 'band',]
    template_name = 'songs/create.html'
    success_url = '../'

class SongUpdateView(generic.UpdateView):
    model = Post
    fields = ['name', 'lyrics', 'band',]
    template_name = 'songs/update.html'
    success_url = '../../'

class SongDeleteView(generic.DeleteView):
    model = Post
    template_name = 'songs/delete.html'
    success_url = '../../'

def create_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment_author = form.cleaned_data['author']
            comment_text = form.cleaned_data['text']
            comment = Comment(author=comment_author,
                            text=comment_text,
                            posts=post)
            comment.save()
            return HttpResponseRedirect(
                reverse('songs:detail', args=(post_id, )))
    else:
        form = CommentForm()
    context = {'form': form, 'post': post}
    return render(request, 'songs/comment.html', context)

class CategoryListView(generic.ListView):
    model = Category
    template_name = 'songs/categories.html'


class CategoryDetailView(generic.DetailView):
    model = Category
    template_name = 'songs/category.html'
# Create your views here.

# def detail_song(request, song_id):
#     song = Post.objects.get(pk=song_id)
#     song = get_object_or_404(Post, pk=song_id)
#     context = {'song': song}
#     return render(request, 'songs/detail.html', context)

# def search_songs(request):
#     context = {}
#     if request.GET.get('query', False):
#         context = {
#             "song_list": [
#                 m for m in movie_data
#                 if request.GET['query'].lower() in m['name'].lower()
#             ]
#         }
#     return render(request, 'songs/search.html', context) # modifique esta linha

# def create_song(request):
#     if request.method == 'POST':
#         form = PostForm(request.POST)
#         if form.is_valid():
#             song_name = form.cleaned_data['name']
#             song_band = form.cleaned_data['band']
#             song_lyrics = form.cleaned_data['lyrics']
#             song = Post(name=song_name,
#                           band=song_band,
#                           lyrics=song_lyrics)
#             song.save()
#             return HttpResponseRedirect(
#                 reverse('songs:detail', args=(song.id, )))
#     else:
#         form = PostForm()
#     context = {'form': form}
#     return render(request, 'songs/create.html', context)

# def list_songs(request):
#     song_list = Post.objects.all()
#     context = {'song_list': song_list}
#     return render(request, 'songs/index.html', context)

# def update_song(request, song_id):
#     song = get_object_or_404(Post, pk=song_id)

#     if request.method == "POST":
#         form = PostForm(request.POST)
#         if form.is_valid():
#             song.name = form.cleaned_data['name']
#             song.band = form.cleaned_data['band']
#             song.lyrics = form.cleaned_data['lyrics']
#             song.save()
#             return HttpResponseRedirect(
#                 reverse('songs:detail', args=(song.id, )))
#     else:
#         form = PostForm(
#             initial={
#                 'name': song.name,
#                 'band': song.band,
#                 'lyrics': song.lyrics
#             })

#     context = {'song': song, 'form': form}
#     return render(request, 'songs/update.html', context)


# def delete_song(request, song_id):
#     song = get_object_or_404(Post, pk=song_id)

#     if request.method == "POST":
#         song.delete()
#         return HttpResponseRedirect(reverse('songs:index'))

#     context = {'song': song}
#     return render(request, 'songs/delete.html', context)

staticpages/views.py
from django.shortcuts import render

from django.http import HttpResponse


def index(request):
    context = {}
    return render(request, 'staticpages/index.html', context)


def about(request):
    context = {}
    return render(request, 'staticpages/about.html', context)

def musicas(request):
    context = {}
    return render(request, 'staticpages/musicas.html', context)

songs/templates/songs/categories.html
{% extends 'base.html' %}
{% block title %}
Categorias 
{% endblock title %}
{% block content %}


<h2>Todas as Categorias</h2>
{% if category_list %}
<section >
    {% for category in category_list %}
    <article >
        <a href="{% url 'songs:category' category.id %}" > <p> {{ category.name}}</p></a>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhuma categoria.</p>
{% endif %}

{% endblock content %}

songs/templates/songs/category.html
{% extends 'base.html' %}
{% block title %}
Categoria {{category.name}}
{% endblock title %}
{% block content %}


<h2>Todas as músicas da Categoria {{category.name}} </h2>
<p>{{category.description}}</p>
{% if category %}
<section >
    {% for post in category.posts.all %}
    <article >
        <a href="{% url 'songs:detail' post.id %}" > <p> {{ post.name}}</p></a>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhuma música relacionada à categoria {{category.name}}.</p>
{% endif %}

{% endblock content %}

songs/templates/songs/comment.html
{% extends 'base.html' %}
{% block title %}
criar comentários
{% endblock title %}
{% block content %}
<h2>Comentar música{{ post.name }} ({{ post.band }})</h2>

<form action="{% url 'songs:comment' post.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Postar Comentário</button>
</form>

<p><a href="{% url 'songs:detail' post.id %}">Voltar para a página da música</a></p>
{% endblock content %}

songs/templates/songs/create.html
{% extends 'base.html' %}
{% block title %}
Adicionar música
{% endblock title %}
{% block content %}
<h2>Inserir Nova música</h2>
<form method="POST" action="{% url 'songs:create' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Criar</button>
</form>

{% endblock content %}

songs/templates/songs/delete.html
{% extends 'base.html' %}
{% block title %}
Deletar {{post.name}}
{% endblock title %}
{% block content %}
<form action="{% url 'songs:delete' post.id %}" method="post">
    {% csrf_token %}
    <p>
        Você tem certeza que deseja apagar a música "{{ post.name }} ({{ post.band }})"?
    </p>
    <button type="submit">Apagar</button>
</form>

{% endblock content %}

songs/templates/songs/detail.html
{% extends 'base.html' %}

{% block title %}
{{ post.name }} ({{ post.band }}
{% endblock title %}

{% block content %}
<h2>Detalhes da música {{ post.name }} ({{ post.band }})</h2>

<section >
    
    <ul>
        <li>Nome: {{ post.name }}</li>
        <li>Banda: {{ post.band }} </li>
        <li>Letra: 
        <p>{{ post.lyrics }} </p></li>
        <li><a href="{% url 'songs:update' post.id %}">Editar</a></li>
        <li><a href="{% url 'songs:delete' post.id %}">Apagar</a></li>

        <h4>Coneça outras músicas dessas bandas:</h4>

        <p>
            {% for category in post.category_set.all %}
            <a href="{% url 'songs:category' category.id %}">{{ category.name }}</a>
            {% endfor %}
        </p>

    </ul>
</section>

<hr>

<section>
    <header>
        <h3>Comentários</h3>
    </header>
    <ul>
        {% if post.comment_set.all %}
            {% for comment in post.comment_set.all %}
                <figure>
                    <blockquote>
                        "{{ comment.text }}"
                    </blockquote>
                    <figcaption>—{{ comment.author }}
                </figure>
            {% endfor %}
        {% else %}
            <p>Ainda não existe nenhum comentário para essa música.</p>
        {% endif %}
    </ul>


    
<hr>

<a href="{% url 'songs:comment' post.pk %}"><button>Crie seu comentário</button></a>
</section>





{% endblock content %}

songs/templates/songs/index.html
{% extends 'base.html' %}
{% block title %}
Músicas
{% endblock title %}
{% block content %}

<section>
    
    <p>Não encontrou a música? <a href="{% url 'songs:create' %}">Adicionar Nova música</a></p>
</section>
<h2>Todas as músicas</h2>
{% if post_list %}
<section >
    {% for post in post_list %}
    <article >
        <a href="{% url 'songs:detail' post.id %}" > <p>música {{ post.name}}</p></a>
        <p>{{ post.name }} ({{ post.band }})</p>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhuma música.</p>
{% endif %}

{% endblock content %}

songs/templates/songs/search.html
{% extends 'base.html' %}

{% block content %}
<h2>Busca de músicas por Nome</h2>
<form action="{% url 'songs:search' %}">
    <p>
        <label for="id_query">Título:</label>
        <input type="text" name="query" id="id_query" />
    </p>
    <button type="submit">Buscar</button>
</form>


<h2>Resultado da Busca</h2>
{% if song_list %}
<section class="lista-de-cards">
    {% for movie in song_list %}
    <article class="card">
        <img src="{{ movie.poster_url }}" alt="Poster do filme {{ movie.name}}">
        <p>{{ movie.name }} ({{ movie.release_year }})</p>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhuma música para a busca.</p>
{% endif %}

{% endblock content %}

songs/templates/songs/update.html
{% extends 'base.html' %}
{% block title %}
Editar {{post.name}}
{% endblock title %}
{% block content %}
<h2>Atualizar Dados da música {{ post.name }}({{ post.band}})</h2>
<form method="POST" action="{% url 'songs:update' post.id%}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Atualizar</button>
</form>

{% endblock content %}

staticpages/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock %} | Curiosidades Russas
    </title>
</head>

<body>
    <header id="cabecalho-principal">
        <a href="{% url 'index' %}">
            <p>WTF</p>
        </a>
        <nav id="navegacao-principal">
            <ul>
                <li><a href="{% url 'about' %}">Sobre</a></li>
                <li><a href="{% url 'musicas' %}">Músicas</a></li>
            </ul>
        </nav>

    </header>
    <main id="conteiner-principal">
        {% block content %}
        {% endblock content %}
    </main>
    <footer id="rodape-principal">
        <p>
            <small>Copyright 2021</small>
        </p>
    </footer>
</body>

</html>

staticpages/templates/staticpages/about.html
{% extends 'base.html' %}

{% block title %}
Sobre
{% endblock title %}

{% block content %}
<h2>Sobre este site</h2>
<p>Esta página foi escrita para ajudar os entusiastas da língua russa a se enturmar mais com a escrita e a música antes de adentrar na gramática </p>
{% endblock content %}

staticpages/templates/staticpages/index.html
{% extends 'base.html' %}

{% block title %}
Página Inicial
{% endblock title %}

{% block content %}
<p>Desejamos as boas-vindas ao nosso site!</p>

<p>Добро пожаловать!</p>

<p>Aqui você poderá saber algumas curiosidades sobre a cultura russa, como:</p>

<p>- Alfabeto</p>

<p>- Músicas</p>

<p>Esperamos que se divirta! Спасибо!</p>
{% endblock content %}

staticpages/templates/staticpages/musicas.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
Músicas
{% endblock title %}

{% block content %}


<p>Aqui você encontrará algumas músicas de origem russa e bielorussa, classificadas majoritariamente como post-punk.

    As músicas podem ser apreciadas por qualquer um, tanto falantes, como estudantes ou até mesmo não falantes de russo, já que você pode utilizar a melodia e o vocal que não entende para se concentrar nos estudos por exemplo ou apenas para se distrair, funcionando analogamente a gênero Lo-fi. espero que goste da minha seleção :)</p>
    
    
    <h3>Bandas:</h3>
    
    <div class="bandas-container">
        <div class ="child-1">
            <img src="{% static 'peremotka.jpg' %}" style="max-width: 150px;" alt="peremotka">
        </div>
        <div class ="child-2">
            <h4>Banda Перемотка</h4>
            <p>Как тебя покорить</p>
            <p>Супермарио</p>
            <p>Старое кино</p>
            <p>Я видел сон</p>
        </div>
    </div>
    <div class="bandas-container">
        <div class ="child-1">
            <img src="{% static 'ploho.jpg' %}" style="max-width: 150px;" alt="ploho">
        </div>
        <div class ="child-2">
            <h4>Banda ploho</h4>
            <p>Молодость</p>
            <p>Закладка</p>
            <p>Танцы в темноте</p>
            <p>Горький опыт</p>
    
        </div>
    </div>
    <div class="bandas-container">
        <div class ="child-1">
            <img src="{% static 'molchat.jpg' %}" style="max-width: 150px;" alt="molchat">
        </div>
        <div class ="child-2">
            <h4>Banda Молчат Дома</h4>
            <p>Тишина</p>
            <p>Танцевать</p>
            <p>По краю острова</p>
            <p>Судно</p>
    
        </div>
        
    </div>
    
    {% endblock content %}

templates/base.html
{% load static %} <!-- adicione esta linha -->

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock %} | Curiosidades Russas
    </title>
    <link href="https://fonts.googleapis.com/css?family=Inter&display=swap" rel="stylesheet" /> <!-- adicione esta linha -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}"> <!-- adicione esta linha -->
</head>

<body>
    <header id="cabecalho-principal">
        <a href="{% url 'index' %}"> <img src="{% static 'logo.svg' %}"> </a> <!-- adicione esta linha -->
        <nav id="navegacao-principal">
            <ul>
                <li><a href="{% url 'songs:index' %}">Músicas</a></li> 
                <li><a href="{% url 'about' %}">Sobre</a></li>
                <li><a href="{% url 'musicas' %}">Minha seleção</a></li>
                <li><a href="{% url 'songs:categories' %}">Categorias</a></li>
            </ul>
        </nav>

    </header>
    <main id="conteiner-principal">
        {% block content %}
        {% endblock content %}
    </main>
    <footer id="rodape-principal">
        <p>
            <small>Copyright 2021</small>
        </p>
    </footer>
</body>

</html>